package contenttypes

//goland:noinspection GoUnusedConst, SpellCheckingInspection, GrazieInspection
const (
	Model3Mf                          = "model/3mf"
	ModelE57                          = "model/e57"
	ModelExample                      = "model/example"
	ModelGltfBinary                   = "model/gltf-binary"
	ModelGltfJson                     = "model/gltf+json"
	ModelJt                           = "model/JT"
	ModelIges                         = "model/iges"
	ModelMesh                         = "model/mesh"
	ModelMtl                          = "model/mtl"
	ModelObj                          = "model/obj"
	ModelPrc                          = "model/prc"
	ModelStep                         = "model/step"
	ModelStepXml                      = "model/step+xml"
	ModelStepZip                      = "model/step+zip"
	ModelStepXmlZip                   = "model/step-xml+zip"
	ModelStl                          = "model/stl"
	ModelU3D                          = "model/u3d"
	ModelVndBary                      = "model/vnd.bary"
	ModelVndCld                       = "model/vnd.cld"
	ModelVndColladaXml                = "model/vnd.collada+xml"
	ModelVndDwf                       = "model/vnd.dwf"
	ModelVndFlatland3Dml              = "model/vnd.flatland.3dml"
	ModelVndGdl                       = "model/vnd.gdl"
	ModelVndGsGdl                     = "model/vnd.gs-gdl"
	ModelVndGtw                       = "model/vnd.gtw"
	ModelVndMomlXml                   = "model/vnd.moml+xml"
	ModelVndMts                       = "model/vnd.mts"
	ModelVndOpengex                   = "model/vnd.opengex"
	ModelVndParasolidTransmitBinary   = "model/vnd.parasolid.transmit.binary"
	ModelVndParasolidTransmitText     = "model/vnd.parasolid.transmit.text"
	ModelVndPythaPyox                 = "model/vnd.pytha.pyox"
	ModelVndRosetteAnnotatedDataModel = "model/vnd.rosette.annotated-data-model"
	ModelVndSapVds                    = "model/vnd.sap.vds"
	ModelVndUsda                      = "model/vnd.usda"
	ModelVndUsdzZip                   = "model/vnd.usdz+zip"
	ModelVndValveSourceCompiledMap    = "model/vnd.valve.source.compiled-map"
	ModelVndVtu                       = "model/vnd.vtu"
	ModelVrml                         = "model/vrml"
	ModelX3DVrml                      = "model/x3d-vrml"
	ModelX3DFastinfoset               = "model/x3d+fastinfoset"
	ModelX3DXml                       = "model/x3d+xml"
)
